version: '3.9'

services:
  armnavigation:
    build:
      context: ./ArmNavigation
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - POSTGRES_CONNECTION_STRING=Host=postgres;Port=5432;User Id=admin;Password=admin;Database=ArmNavigation;SearchPath=arm_navigation_schema;Include Error Detail=true
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - armnavigation_net

  postgres:
    image: postgres:16
    container_name: armnavigation_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ArmNavigation
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - armnavigation_net

volumes:
  postgres_data:

networks:
  armnavigation_net:
    driver: bridge
